### ISSUE TITLE
doctype

### ISSUE THREAD

**Issue by michal-bootcamp** [JoannaKu/Java-Script-3#1]
dodaj doctype do html

**Comment by JoannaKu** [comment]
poprawione :)

**Comment by michal-bootcamp** [comment]
ok :) usun jeszcze komentarz z html `<!-- index.html -->` i wyrownaj wciecia (tag html jest pierwszym rodzicem innych tagow wiec nie powinien byc wciety)

**Comment by JoannaKu** [comment]
zrobione :)
